BEGIN;

INSERT INTO public.actors (name, gender, birthdate, is_del) VALUES
                                                         ('Tom Hanks', 'male', '1956-07-09', false),
                                                         ('Robert De Niro', 'male', '1943-08-17', false),
                                                         ('Meryl Streep', 'female', '1949-06-22', false),
                                                         ('Denzel Washington', 'male', '1954-12-28', false),
                                                         ('Julia Roberts', 'female', '1967-10-28', false),
                                                         ('Brad Pitt', 'male', '1963-12-18', false),
                                                         ('Angelina Jolie', 'female', '1975-06-04', false),
                                                         ('Leonardo DiCaprio', 'male', '1974-11-11', false),
                                                         ('Sandra Bullock', 'female', '1964-07-26', false),
                                                         ('Will Smith', 'male', '1968-09-25', false),
                                                         ('Keanu Reeves', 'male', '1964-09-02', false),
                                                         ('Jennifer Aniston', 'female', '1969-02-11', false),
                                                         ('George Clooney', 'male', '1961-05-06', false),
                                                         ('Nicole Kidman', 'female', '1967-06-20', false),
                                                         ('Tom Cruise', 'male', '1962-07-03', false),
                                                         ('Halle Berry', 'female', '1966-08-14', false),
                                                         ('Johnny Depp', 'male', '1963-06-09', false),
                                                         ('Charlize Theron', 'female', '1975-08-07', false),
                                                         ('Matt Damon', 'male', '1970-10-08', false),
                                                         ('Kate Winslet', 'female', '1975-10-05', false),
                                                         ('Hugh Jackman', 'male', '1968-10-12', false),
                                                         ('Scarlett Johansson', 'female', '1984-11-22', false),
                                                         ('Samuel L. Jackson', 'male', '1948-12-21', false),
                                                         ('Emma Stone', 'female', '1988-11-06', false),
                                                         ('Ryan Reynolds', 'male', '1976-10-23', false),
                                                         ('Emma Watson', 'female', '1990-04-15', false),
                                                         ('Chris Hemsworth', 'male', '1983-08-11', false),
                                                         ('Natalie Portman', 'female', '1981-06-09', false),
                                                         ('Chris Pratt', 'male', '1979-06-21', false),
                                                         ('Jennifer Lawrence', 'female', '1990-08-15', false),
                                                         ('Mark Wahlberg', 'male', '1971-06-05', false),
                                                         ('Saoirse Ronan', 'female', '1994-04-12', false),
                                                         ('Chris Evans', 'male', '1981-06-13', false),
                                                         ('Margot Robbie', 'female', '1990-07-02', false),
                                                         ('Daniel Craig', 'male', '1968-03-02', false),
                                                         ('Gal Gadot', 'female', '1985-04-30', false),
                                                         ('Jason Momoa', 'male', '1979-08-01', false),
                                                         ('Zendaya', 'female', '1996-09-01', false),
                                                         ('Ethan Hawke', 'male', '1970-11-06', false),
                                                         ('Viola Davis', 'female', '1965-08-11', false),
                                                         ('Benedict Cumberbatch', 'male', '1976-07-19', false),
                                                         ('Cate Blanchett', 'female', '1969-05-14', false),
                                                         ('Tom Hardy', 'male', '1977-09-15', false),
                                                         ('Emily Blunt', 'female', '1983-02-23', false),
                                                         ('Jake Gyllenhaal', 'male', '1980-12-19', false),
                                                         ('Anne Hathaway', 'female', '1982-11-12', false),
                                                         ('Christian Bale', 'male', '1974-01-30', false),
                                                         ('Jennifer Garner', 'female', '1972-04-17', false),
                                                         ('Idris Elba', 'male', '1972-09-06', false),
                                                         ('Penelope Cruz', 'female', '1974-04-28', false);
COMMIT;